apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oclb8w7rh-python
  janus-idp.io/tekton: oclb8w7rh-python
  backstage.io/kubernetes-id: oclb8w7rh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oclb8w7rh-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
